keys:
  - &users:
    - &ggantiva age1mthykpauy7elxz3dftg2n9pgpkwxj5v9qfdnn6847fy9k3euqu9qx5w8tz
  - &hosts:
    - &h610m age1e9l0unaq0p79lq2jlndxw4hvrh5g5nnpnsgzlgyykx64838eduusyl2ldv
    - &hp705 age100xe2ljvev3yda2ppedjun3xucqye5gxgh8vxnuxu9tw0vruz4lqkngv7c
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *ggantiva
      - *h610m
      - *hp705
